name: Build & test project

on:
  pull_request:
    branches: [main]
    paths:
      - src/main/**
      - src/test/**
      - pom.xml

jobs:
  test:
    name: Build & run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: microsoft
          cache: maven
      - name: Run tests
        run: mvn -B test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target
          retention-days: 1

  linters:
    name: Report linting results
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - name: Publish CheckStyle report
        uses: jwgmeligmeyling/checkstyle-github-action@v1.2
        with:
          name: CheckStyle report
          path: target/checkstyle-result.xml
      - name: Publish SpotBugs report
        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          name: SpotBugs report
          path: target/spotbugsXml.xml

  surefire:
    name: Report test results
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - name: Publish JUnit report
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: JUnit report
          exclude_sources: target,docs,.idea
          report_paths: target/surefire-reports/TEST-*.xml

  coverage:
    name: Report test coverage
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - name: Publish JaCoCo report
        uses: madrapps/jacoco-report@v1.3
        with:
          title: JaCoCo report
          update-comment: true
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          paths: target/site/jacoco/jacoco.xml
          token: ${{github.token}}
